export const ALL_PROMPTS = [
  // ── Quiplash XL / Quiplash 1 ──────────────────────────────────────────────
  "Quais são as duas palavras que os passageiros nunca gostariam de ouvir um piloto dizer?",
  "Você nunca entraria em uma montanha-russa chamada ___",
  "O segredo para uma vida feliz",
  "Se um treinador vencedor leva um Gatorade jogado na cabeça, o que deve ser jogado no treinador perdedor?",
  "Cite um perfume de vela projetado especificamente para Kim Kardashian",
  "Você nunca deve dar álcool a ___",
  "Todo mundo sabe que os macacos odeiam ___",
  "A maior desvantagem de viver no Inferno",
  "As verdadeiras últimas palavras de Jesus",
  "A pior coisa para uma bruxa malvada transformar você",
  "O sabor Skittles que perdeu o corte",
  "Na sua noite de núpcias, seria horrível descobrir que a pessoa com quem você se casou é ___",
  "Um nome para um musical da Broadway realmente ruim",
  "A primeira coisa que você faria depois de ganhar na loteria",
  "O que realmente está causando o aquecimento global?",
  "Um nome para uma marca de fraldas para adultos de grife",
  "Diga o nome de um drama de TV sobre um médico vampiro",
  "Algo que os esquilos provavelmente fazem quando ninguém está olhando",
  "O crime que você cometeria se pudesse escapar impune",
  "Crie um ótimo título para o próximo filme estranho de sexo adolescente",
  "Do que a Mona Lisa está sorrindo?",
  "Um nome terrível para um navio de cruzeiro",
  'O que FDR quis dizer foi "Não temos nada a temer, mas ___"',
  "Crie um título para uma versão adulta de qualquer videogame clássico",
  "O nome de uma fonte que ninguém jamais usaria",
  "Algo que você nunca deve colocar em uma ferida aberta",
  "Os cientistas dizem que houve erosão, mas todos sabemos que o Grand Canyon foi na verdade feito por ___",
  "A verdadeira razão pela qual os dinossauros morreram",
  "Invente o nome de um país que não existe",
  "A melhor maneira de se aquecer em uma noite fria de inverno",
  "Um curso universitário que você não vê em muitas universidades",
  "O que tornaria o beisebol mais divertido de assistir?",
  "A melhor coisa de ir para a prisão",
  "O melhor título para um novo hino nacional dos EUA",
  "Pense no nome de um livro que venderia um milhão de cópias imediatamente",
  "O que você faria se ficasse sozinho na Casa Branca por uma hora?",
  "Invente uma palavra substituta adequada para toda a família que você possa dizer em vez de um palavrão real",
  "Um nome melhor para testículos",
  "O nome da rena que Papai Noel não escolheu para puxar seu trenó",
  "Qual a primeira coisa que você faria se pudesse viajar no tempo?",
  "O nome de uma pizzaria onde você nunca deve pedir",
  "Um nome não muito assustador para um pirata",
  "Invente um nome para uma cerveja feita especialmente para macacos",
  "A melhor coisa de viver em um iglu",
  "A pior maneira de ser assassinado",
  "Algo que você não deveria dar ao seu parceiro no Dia dos Namorados",
  "Uma coisa perigosa de se fazer enquanto dirige",
  "Algo que você não deveria usar em uma entrevista de emprego",
  "A principal razão pela qual os pinguins não podem voar",
  "Usando apenas duas palavras, um novo lema estadual para o Texas",
  "A coisa mais difícil de ser o Batman",
  "Uma ótima maneira de matar o tempo no trabalho",
  'Invente um programa de TV realmente ruim que comece com "Baby"',
  "Por que a Torre de Pisa se inclina?",
  "O que há de errado com essas crianças hoje?",
  'Uma grande nova invenção que começa com "Automático"',
  'Invente um pênalti de futebol muito ruim que comece com "Intencional"',
  "Um café Starbucks que nunca deveria existir",
  "Há Grifinória, Corvinal, Sonserina e Lufa-Lufa, mas qual é a casa de Hogwarts da qual poucos já ouviram falar?",
  "As piores palavras a dizer para a abertura de um elogio em um funeral",
  "Algo que você nunca deve usar como lenço",
  "Invente um feriado que você acha que todos iriam gostar",
  "A melhor notícia que você pode receber hoje",
  "Normalmente é bacon, alface e tomate, mas invente um BLT que você não gostaria de comer",
  "A pior coisa com que você poderia encher um colchão de cama",
  "Uma ótima frase de abertura para iniciar uma conversa com um estranho em uma festa",
  "Algo com que você gostaria de encher uma piscina",
  "Senha do Wi-Fi de Miley Cyrus, possivelmente",
  "Se você pudesse dar ao bebê de outra pessoa o nome de qualquer coisa estranha que você quisesse, como você o nomearia?",
  "Uma coisa divertida para se pensar durante o sexo medíocre",
  "Você sabe que terá uma péssima viagem de táxi quando ___",
  "De onde vêm os bebês?",
  'O terrível destino do boneco de neve Olaf na versão do diretor de "Frozen"',
  "Às vezes, depois de um longo dia, você só precisa ___",
  "A pior maneira de soletrar Mississippi",
  "Dê-me uma boa razão pela qual eu não deveria bater em você agora",
  "A melhor linha de pick-up para um mixer de solteiros idoso",
  "Um bom nome artístico para uma stripper chimpanzé",
  "O melhor lugar para enterrar todos esses corpos",
  "Um lugar onde um dedo não deveria ir",
  "Crie um nome para a postura de ioga mais difícil conhecida pela humanidade",
  "O que está escondido debaixo da sua cama quando você dorme?",
  "Um ótimo nome para uma praia de nudismo no Alasca",
  "Invente o título de um filme baseado na primeira vez que você fez sexo",
  "Uma placa personalizada que um idiota em um carro caro teria",
  "Um bom nome falso para usar ao fazer check-in em um hotel",
  "Uma boa frase de efeito para gritar toda vez que você terminar de fazer cocô",
  'Seu bordão pessoal se você estivesse em um daqueles programas "Real Housewives"',
  "Algo que você nunca deveria enfiar na bunda",
  "Um nome terrível para um palhaço",
  "Uma coisa inadequada para fazer em um cemitério",
  "Como frango empanado ou frango poppers, um novo nome de aperitivo para o seu divertido restaurante temático: frango ___",
  "Coisa que você ficaria mais surpreso se um dentista encontrasse em sua boca",
  "Renomeie Winnie-the-Pooh para algo mais apropriado/descritivo",
  'Nomeie a sequência de "Titanic", se houver. "Titânico 2: ___"',
  "Um uso alternativo para uma banana",
  "O que você imagina é um ingrediente não anunciado na maioria dos cachorros-quentes",
  "Dê um nome ao seu novo estabelecimento de corte de cabelo",
  "Algo que daria um chapéu horrível",
  "Quantos macacos são macacos demais?",
  "Algo que você ficaria surpreso em ver um burro fazer",
  "O título que você criaria se estivesse escrevendo a música tema das Olimpíadas",
  "Algo que você nunca deveria dizer para sua mãe",
  "Invente um nome para um coquetel novo e muito viril",
  "Os três ingredientes do pior smoothie de todos os tempos",
  "A melhor coisa para usar quando você estiver sem papel higiênico",
  "Crie um nome mais cativante e comercializável para a Bíblia",
  "O nome mais presidencial que você possa imaginar (esse ainda não é o nome de um presidente)",
  "Uma boa maneira de ser demitido",
  "Se não temos dinheiro para enterrar ou cremar você, o que devemos fazer com seu corpo?",
  "Diga o nome do oitavo anão, que foi cortado no último minuto",
  "Um bom lugar para esconder melecas",
  'Crie um nome para um novo programa de TV com a palavra "Spanky"',
  "Um truque divertido para pregar no Papa",
  "Onde você acha que a carne realmente está?",
  "Algo que seria divertido jogar fora da Torre Eiffel",
  "Escreva uma manchete de jornal que realmente chame a atenção das pessoas",
  'O pior cargo que começa com "Assistente"',
  "A última pessoa que você consideraria convidar para sua festa de aniversário",
  "A coisa mais nojenta que você colocaria na boca por US$ 18",
  "O nome de um novo perfume de Betty White",
  "O pior nome para um robô",
  "Os primeiros nomes de cada um dos seus mamilos",
  "O nome mais embaraçoso para um cachorro",
  "A pior coisa para descobrir no seu burrito",
  "Uma coisa que nunca se deve fazer no primeiro encontro",
  "A senha do Twitter de Ozzy Osbourne, provavelmente",
  "Quem soltou os cachorros?",
  "Qual é o gosto dos veganos?",
  "Um item NÃO encontrado na bolsa de Taylor Swift",
  "Diga o nome de uma nova banda de reggae composta inteiramente por galinhas",
  "Diga o nome de um livro infantil escrito por alguém que odeia crianças",
  "O nome da sua nova empresa de encanamento",
  "Invente uma palavra que descreva o som de peidar em uma tigela de macarrão com queijo",
  "Um novo sabor de sorvete que ninguém jamais pediria",
  "Diga o nome de um novo filme estrelado por uma cabra falante que é presidente dos Estados Unidos",
  "Algo que não funcionaria bem como molho para chips de tortilla",
  "Se Deus tem senso de humor, ele dá as boas-vindas às pessoas no céu dizendo ___",
  "O nome de uma loja de roupas para duendes com excesso de peso",
  "Algo perturbador que você poderia dizer ao cara da TV a cabo enquanto ele instala seu serviço de televisão",
  "A pior coisa que poderia saltar de um bolo de despedida de solteiro",
  "Crie um nome para uma nova cerveja comercializada para bebês",
  "Um tema terrível para um baile de formatura do ensino médio",
  "Invente um nome para um filme pornô mudo da década de 1920",
  "Algo que você não deveria sussurrar para sua avó",
  "Um nome terrível para um gangster dos anos 1930",
  "Uma coisa divertida de gritar quando um bebê está nascendo",
  "O pior segredo de família que poderia ser revelado no jantar de Ação de Graças",
  "O nome de um papel higiênico projetado especificamente para a Rainha da Inglaterra",
  "Algo que você provavelmente encontraria muito na geladeira de Deus",
  "A pior pessoa para narrar o audiolivro de \"Cinquenta Tons de Cinza\"",
  "Uma decoração de gramado que certamente deixará os vizinhos furiosos",
  "A pior coisa a dizer ao tentar adotar um animal de estimação",
  "Um bom nome para uma padaria erótica",
  "As pessoas não respeitariam tanto He-Man se, para ganhar seu poder, ele erguesse sua espada e gritasse ___",
  "Coisa divertida de fazer se ficar trancado no shopping durante a noite",
  "A pior pessoa para receber um banho de esponja",
  "As calças ficariam muito melhores se ___",
  "O recorde mundial do Guinness mais incrível para quebrar",
  "Uma maneira pouco conhecida de tirar chiclete do cabelo",
  "É ruim ser enterrado vivo. É pior ser enterrado vivo com ___",
  "Algo que não funcionaria tão bem quanto esquis",
  'Um título rejeitado para "O Bom, o Mau e o Feio" foi "O Bom, o Mau e o ___"',
  "O que dizer para sair do serviço de júri",
  "O que a Estátua da Liberdade esconde sob esse manto",
  "Só há um momento em que o assassinato é aceitável e é quando ___",
  "Pegue qualquer restaurante conhecido e mude ligeiramente seu nome para algo inapropriado",
  "Fato pouco conhecido: o governo permite que a manteiga de amendoim contenha até 10% ___",
  "Um bom sinal de que sua casa está assombrada",
  "Um nome cativante para um banco de esperma",
  "Uma ocupação ruim para um robô ter",
  "Uma sequência da pintura Dogs Playing Poker",
  "O outro trabalho da Fada do Dente",
  "Fato pouco conhecido: uma área secreta na Casa Branca é a sala ___",
  "Uma invenção de Thomas Edison que nunca pegou",
  "Um lugar ruim para nadar nu",
  "Que horas são?",
  "Um presente de aniversário que você não deveria ganhar para sua avó",
  "Um pequeno lema pelo qual todos deveriam viver",
  "Invente uma tradição de Natal que certamente pegará",
  "Uma coisa ruim para gritar durante a igreja",
  "O pensamento mais nada sexy que você pode ter",
  "Uma boa melhoria a ser feita no Monte. Rushmore",
  "A melhor maneira de começar o dia",
  "O pior nome para um acampamento de verão",
  "Algo que piora com a adição de queijo",
  "Três coisas são certas na vida: Morte, Impostos e ___",
  "Uma maneira mais rápida de voltar da Terra de Oz para casa é bater os calcanhares três vezes e dizer ___",
  "O primeiro mandamento da nova religião que você iniciou",
  "Invente um nome para uma banda de rock formada inteiramente por patinhos",
  "Algo que atualmente é legal e deveria ser banido",
  'Uma palavra que nunca deveria seguir "Beef"',
  "A música perfeita para cantarolar no banheiro",
  "Uma coisa ruim para dizer a um policial enquanto ele passa uma multa por excesso de velocidade para você",
  "Algo que você não deveria comprar no Craigslist",
  "Pegue o nome de qualquer presidente dos EUA e transforme-o em algo inapropriado",
  "Todos podemos concordar que ___",
  "O nome que você daria a um porco realmente deprimido",
  "Um ótimo nome para ter em uma identidade falsa.",
  "Com o que os robôs sonham",
  "O que realmente aconteceu com Amelia Earhart",
  "Quão longe é muito longe?",
  "Se no começo você não conseguir...",
  'Termine esta frase: Quando eu for rico, minha mansão terá um quarto chamado Sala ___',
  "Algo que você ficaria surpreso ao ver sair de uma espinha que você estourou",
  "A música de hoje precisa de mais ___",
  "Um truque divertido para pregar ao seu médico",
  "Um lugar ruim para o seu foguete cair seria O Planeta do ___",
  "Um slogan de campanha ruim para um congressista",
  "A maneira mais legal de morrer",
  "Duas pessoas da história que definitivamente deveriam fazer sexo",
  "O nome de uma versão totalmente masculina do Hooters",
  "Um apelido pouco conhecido para Nova Orleans",
  "Uma maneira única de escapar da prisão",
  "O título de um novo vídeo de gato no YouTube que certamente se tornará viral",
  "Um presente que ninguém iria querer: O Clube ___ do Mês",
  'Uma ideia de negócio tão maluca que é brilhante para lançar em "Shark Tank"',
  "Uma terrível fortuna de biscoitos da sorte",
  'Seria assustador ler na embalagem de um alimento: "Pode conter oligoelementos de ___"',
  "O que uma mensagem de sexo de cachorro pode dizer",
  "Algo que o diabo tem medo",
  "A CBS deveria transmitir um programa de TV sobre advogados que também são ___",
  "Uma ótima coisa para gritar antes de pular de um avião",
  "O que você espera que o Mars Rover encontre",
  "Uma manchete do TMZ que você realmente deseja ver",
  "Algo que fará você ser expulso de um Wendy's",
  "Uma frase rejeitada para um daqueles doces de coração do Dia dos Namorados",
  "Para onde vão as meias perdidas",
  "O primeiro sinal de que você está velho",
  "O nome de um coquetel para caipiras",
  "Graffiti que você pode encontrar em um jardim de infância",
  "A pior coisa para vestir no julgamento",
  "Uma cor de giz de cera rejeitada",
  "Uma crítica irada que você daria a este jogo (Quiplash)",
  "Maus conselhos para recém-formados",
  "A melhor maneira de saber se alguém está morto",
  "Um talento terrível para se ter no concurso Miss América",
  "Manchete de amanhã: Cientistas ficam chocados ao descobrir que ___",
  "O pior material para fazer um boneco de neve",
  "Um bordão terrível de locutor esportivo para quando alguém enterra uma bola de basquete",
  "A primeira coisa que um porco diria se pudesse falar",
  "Uma entrada de emprego surpreendente no currículo de Abraham Lincoln",
  "A pior forma para um biscoito animal",
  "Uma coisa estranha de encontrar na mesa de cabeceira dos seus avós",
  "O pior nome para uma loja grande e alta",
  "Algo que você gritaria para incomodar os golfinhos no Sea World",
  "Um novo nome para kumquats",
  "O nome de um shampoo para hippies",
  "O verdadeiro segredo para viver até os 100 anos",
  "O que realmente acontece se você arrancar a etiqueta do colchão",
  "Uma primeira linha ruim para seu discurso de posse presidencial",
  "Uma coisa divertida para fazer com uma tigela de pudim",
  "Outro uso para espaguete cozido",
  "Uma maneira física estranha de cumprimentar alguém",
  "O pior nome para um salão de bronzeamento",
  'A pior palavra que pode vir antes de "peido"',
  "Um mau substituto para uma escova de dentes",
  "Um truque que você não deveria ensinar ao seu cachorro",
  "Um nome para um hotel realmente barato",
  "A segunda coisa dita na lua",
  "Por que tão sério?",
  "Uma atração turística no Inferno",
  "O pior nome para uma montanha",
  "Um pensamento que mantém o Papai Noel acordado à noite",
  "A melhor coisa de ser realmente burro",
  "Invente um nome para um molho de salada de Lindsay Lohan",
  "O que eles chamam de cocô na Terra de Oz",
  'Uma maneira completamente errada de escrever “Jennifer Aniston”',
  "Você sabe que está realmente bêbado quando...",
  "Um animal que Noah não deveria ter salvo",
  "O maior segredo que o governo guarda",
  "Outro uso para molho",
  "O pior nome para um artista de rap",
  "Um comentário irritado na Internet no site de uma loja de animais",
  "Uma forma rejeitada para Marshmallow Peeps",
  "Algo que nunca deveria ser feito em casa",
  "O pior nome para uma funerária",
  "O que Chewbacca realmente tem gritado todos esses anos",
  "A pior característica do carro que termina com “suporte”",
  "Um tweet de um homem das cavernas",
  "Um ótimo apelido para os pelos das suas axilas",
  "Escolha qualquer nome de cidade e faça com que pareça sujo",
  "O que você quer que sua lápide leia",
  "Um slogan para deixar todos entusiasmados com o milho",
  "Nunca acaba bem quando você mistura ___ e ___",
  "A melhor razão para ir para a Austrália",
  "O concurso de beleza que ninguém quer ver: Senhorita ___",
  "A refeição perfeita seria um ___ recheado com ___ recheado com ___",
  "O que há de preto, branco e vermelho?",
  "Um fato pouco conhecido sobre o Jolly Green Giant",
  "A pior coisa para encontrar crescendo em seu pescoço",
  "EUA! EUA! A América ainda é a número um em...",
  "Um bom nome para uma colônia de nudistas de idosos",
  "Você nunca deve ___ e ___ ao mesmo tempo",
  "O que uma árvore está pensando o dia todo?",
  "O que você chama de bebê sasquatch",
  "Um bom nome para um robô sexual",
  "Um mau motivo para ligar para o 911",
  "Cite a próxima grande doença sexualmente transmissível",
  "A pior coisa sobre o Canadá",
  "Uma coisa estranha para se manter como animal de estimação",
  "O que os gatinhos diriam se pudessem falar",
  "Uma placa que você provavelmente não deveria colocar em seu quintal",
  "O que os cães pensam quando veem pessoas nuas",
  "A coisa mais nojenta que você pode encontrar no fundo de uma piscina",
  "O pior nome para um SUV",
  "Um bom uso para recortes de unhas",
  "O título do pornô mais chato de todos os tempos",
  "Algo que você não deveria rechear com queijo",
  "Algo que Godzilla faz quando está bêbado",
  "Conversa fiada que você ouviria em uma competição de xadrez",
  "Dica: Nunca coma em um lugar chamado Kentucky Fried ___",
  "Algo ouvido na Última Ceia",
  "O nome de uma espécie de dinossauro que você não gostaria de conhecer",
  "A pior maneira de voar: ___ Companhias Aéreas",
  "Fato pouco conhecido: ao longo da vida, uma pessoa comum come acidentalmente dez ___",
  "Um ótimo nome de animal de estimação para um verme parasita que vive em seu ouvido",
  "Uma pegadinha que os juízes da Suprema Corte provavelmente pregam uns nos outros",
  "Uma coisa maluca de se encontrar durante uma colonoscopia",
  "Uma palavra que deveria estar no dicionário, mas não está",
  "Conselho: Nunca enfie a língua em ___",
  "O nome perfeito para uma segunda cabeça que brota no seu ombro",
  "Algo que um meteorologista poderia gritar se quebrasse completamente durante a previsão do tempo",
  "O pior conselho que um médico poderia dar",
  "Truque de vida! Reduza suas contas de aquecimento em...",
  "A pior coisa que pode sair do seu banheiro",
  "Ninguém imaginaria que é aqui que o tesouro está enterrado",
  "Como Garfield, o gato dos desenhos animados, acabará morrendo",
  "A pior pizza é a pizza estilo ___",
  "O que fazer quando seu pára-quedas falhar",
  "O sonambulismo pode ser um problema, mas não é tão ruim quanto o sono___",
  "Um bom nome para um cantor country canino",
  "Fato pouco conhecido: o quarto Sábio deu ao menino Jesus o pior presente de todos: ___",
  "Um tema para um calendário de mesa que não venderia muito bem",
  "Um bom nome para um restaurante que serve animais com os rostos ainda estampados",
  "Isso acabou de chegar! A ___ ganhou a eleição e se tornará o novo governador do Texas",
  "A pior fantasia de Halloween para uma criança",
  "Um nome melhor para o Monumento a Washington",
  "Um food truck terrível seria aquele que vende apenas ___",
  "A pior coisa para ouvir durante a cirurgia",
  "Um nome melhor para caspa",
  "O líquido que daria o pior molho para salada",
  'Invente uma palavra que signifique "inventar uma palavra"',
  "Algo que você não quer encontrar na sua meia de Natal",
  "A coisa mais maluca que você pode retocar na sua van",
  "Algo que você adoraria quebrar com uma bola de demolição",
  "O que os cervos usariam como isca se caçassem caçadores",
  "O melhor nome para um rapper obeso",
  "Se os animais assumissem o controle, uma exposição que você veria no zoológico humano",
  "Uma revista que nunca deveria ter uma página central nua",
  "Invente uma palavra para a substância aquosa que sai de um frasco de ketchup quando você o aperta pela primeira vez",
  "Um nome melhor para o jogo Duck Duck Goose",
  "O pior jogo de tabuleiro infantil seria ___ ___ Hipopótamos",
  "O videogame mais chato do mundo",
  "A diferença entre carne bovina grau A e carne bovina grau B",

  // ── Quiplash 2 ─────────────────────────────────────────────────────────────
  "A coisa nojenta que ninguém sabe sobre o coelhinho da Páscoa",
  "Uma coisa é pegar o ouro dele, mas a melhor maneira de deixar um duende louco é ___",
  "Outro uso para cenouras",
  "O que a NASA não nos diz é que durante anos eles observaram ___ através de um poderoso telescópio",
  "A principal razão pela qual as pessoas são reprovadas na escola ninja",
  "O título do emprego dos sonhos definitivo",
  "A única coisa que você consegue lembrar de dentro do útero",
  "Uma arma do crime que deve ser adicionada à próxima versão do jogo Clue",
  "O pior tema para uma slot machine",
  "Uma coisa muito legal de reencarnar como",
  "Soletre o som que um peixe faz ao atingir uma pessoa no rosto",
  "Do que são realmente feitos os nuggets de frango?",
  "Quais são as três maiores palavras da língua inglesa?",
  "O que acontece quando você faz seu 10.000º cocô?",
  "Um nome terrível para um programa de entrevistas matinal",
  'Seria estranho se alienígenas chegassem e a primeira coisa que dissessem fosse "Leve-nos para o seu ___"',
  "Algo incomum de se ver escrito em um box de banheiro",
  "O título de uma sitcom estrelada por uma lontra",
  "A pior linha de assinatura que você poderia ter em seu e-mail",
  "Como o cara do Banco Imobiliário realmente ganhou sua riqueza",
  "A parte mais difícil de viver para sempre",
  "Na sua opinião, os cientistas deveriam trabalhar sem parar para clonar ___",
  'As três coisas que compõem o “cheiro de velho”',
  "O que Adão e Eva REALMENTE fizeram para serem expulsos do Jardim do Éden?",
  "Uma coisa divertida para fazer em um supermercado quando ninguém está olhando",
  "Você sabe que seu filho está crescendo muito rápido quando começa a ___",
  "O que disse o cara que usou o primeiro banheiro",
  "Uma coisa estranha para descobrir ao chegar ao céu: as noites de terça-feira são ___ noite",
  "O que um repórter de trânsito bêbado diria",
  "Uma coisa terrível para anunciar no seu primeiro dia na prisão",
  "O título de um musical que você está feliz por não existir",
  "Uma criatura que você nunca deveria encontrar em um carrossel",
  "Por que cada floco de neve é diferente?",
  "Encontrar dinheiro em uma calça velha é ótimo, mas o que é ainda melhor é descobrir ___",
  "Um grupo que nenhum motorista de ônibus de turismo deseja que seja atribuído ao seu ônibus",
  "A parte mais difícil do namoro em 1892",
  "O nome de uma posição sexual realmente chata é Reverse ___",
  "A pior tatuagem para se ter na bunda consistiria nessas três palavras",
  'Uma péssima desculpa para chegar atrasado ao seu casamento: "Desculpe, eu estava ___"',
  "Uma coisa estranha para um árbitro de beisebol se inclinar e dizer a um receptor",
  "Um evento que você dominaria nas Olimpíadas: os 500 metros ___",
  "Dica: leve seu copo grande de cinema para casa e use-o por ___",
  "Um ingrediente que você definitivamente não deveria encontrar em uma garrafa de água",
  "O pior donut do mundo está cheio de ___",
  "No seu trabalho, você não precisa de um colete à prova de balas, você precisa de um ___colete à prova de balas",
  'A sequência da música "I Saw Mommy Kissing Santa Claus"',
  "O título do livro mais curto já escrito",
  "A coisa mais assustadora que você poderia encontrar em uma caverna",
  "Por que as corujas não nos matam?",
  "Como um cowboy preguiçoso chama seu cavalo",
  "A melhor maneira de sair de um labirinto de milho",
  "O que uma primeira-dama faz o dia todo",
  "A pior coisa que um salva-vidas poderia anunciar aos nadadores próximos",
  "A única coisa que eles não mostram na turnê do Pentágono é a sala secreta ___",
  "A melhor parte de ter muito cabelo nas costas",
  "A melhor maneira de escapar do interior de uma baleia",
  "Um food truck que você pode ver no Texas: ___ On A Stick",
  "O que acontece se você comer muitos cachorros-quentes?",
  "A próxima grande mania dos yuppies: ___ engarrafado",
  "Algo que você pode ouvir em um carro palhaço completamente cheio",
  'O pior erro ortográfico possível de “Zach Galifianakis”',
  "Uma nova tradição do beisebol que você gostaria de ver seria a sétima entrada ___",
  "Algo muito perturbador para tirar da orelha",
  "Num futuro próximo, os cientistas descobrirão que os dinossauros na verdade ___",
  "O que os manequins estão sempre pensando?",
  "Sem dúvida, o pior colega de quarto seria ___",
  "Um carro que nunca venderia é o Honda ___",
  "Nunca leve um primeiro encontro para um ___",
  "Uma frase engraçada para dizer antes de você ser queimado na fogueira",
  "Todo mundo fica bem em uma motocicleta, exceto ___",
  "O que é aquele líquido azul nas bolas Magic 8?",
  "O título do livro que nunca foi retirado da biblioteca",
  "Uma música rejeitada do musical Oklahoma!",
  "Você vai perceber que não deveria ter pegado aquele carona quando ele disser ___",
  "Um bom nome para um parque aquático cristão",
  "Um item que nunca é vendido em uma liquidação de garagem",
  "Seria incrível se você pudesse cultivar ___ em um jardim",
  "Algo que você não quer ver em uma caixa de “achados e perdidos”",
  "A pior coisa que um professor de história poderia dizer",
  "A vaga de estacionamento designada mais estranha seria uma vaga específica para ___",
  "Um nome para um site de namoro para pessoas com mais de 80 anos",
  "Uma pergunta frequente em www.beets.com",
  "Um nome terrível para um ditador",
  "O paraquedismo indoor faz muito mais sentido do que ___ indoor",
  "Você pode dizer que está em um cruzeiro ruim quando o capitão anuncia \"Se você olhar para estibordo, verá ___\"",
  "Para ser autêntica, a pizza estilo nova-iorquina precisa ter muito ___",
  "A marca de um papel higiênico realmente áspero",
  "Você pode dizer que seus pais estão felizes por ter você fora de casa quando eles transformam seu quarto em ___",
  "A maneira mais rápida de se livrar de uma tênia",
  "Uma música country de sucesso para pessoas que se preocupam com o meio ambiente",
  "O que o alienígena da TV dos anos 80, ALF, provavelmente está fazendo agora",
  "Algo que nunca deveria ter recheio de chocolate",
  "Uma coisa inadequada para escrever no elenco de alguém",
  "O que você faria por uma barra Klondike?",
  'O termo médico técnico para "burro do pântano"',
  "Algo que você não esperaria ouvir de um sanduicheiro do Subway",
  "O maior erro que você pode cometer em um buffet livre",
  "Por que você não deveria festejar com Vikings",
  "Uma coisa ruim para um meteorologista de TV dizer durante um alerta de tornado",
  "O nome de um restaurante que só serve carne de grau D",
  "A pior coisa para ver pela janela do seu avião",
  "No futuro, a América mudará seu nome para ___",
  "Por que as preguiças são tão lentas?",
  'Os três ingredientes de uma bebida chamada "The Chicago"',
  "Uma placa de rua que você esperaria ver na Irlanda",
  "Um sinal de que você fez uma plástica no nariz feia",
  "Um procedimento que nem o cirurgião plástico mais nojento fará",
  "A aula mais difícil que você pode fazer no Clown College",
  "Edward Mãos de Tesoura teria sido um filme muito diferente se se chamasse Edward ___mãos",
  "Uma razão incomum para duelar com alguém",
  "Alguém que seria um péssimo goleiro de futebol",
  "Nome de loja de lingerie voltada para mulheres muito conservadoras",
  "Um nome terrível para uma rua",
  "Uma imagem secreta escondida na nota de US$ 1",
  "Um mau substituto para o fio dental",
  "O desafio mais assustador que nunca foi feito no Fear Factor",
  "O que as vacas costumam dizer quando mugem",
  "Uma linha ruim para ter no seu cartão de visita",
  "Nunca ___ depois de aplicar a loção",
  "Um nome que sempre faria um professor rir durante a chamada",
  "Algo em que você nunca deve pensar enquanto medita",
  "Um fato nutricional que você encontraria em uma lata de merda",
  "Se você realmente ouvir com atenção, ouvirá uma concha dizer isso",
  "Um bom uso para um shopping abandonado",
  "O patrocinador da NASCAR mais estranho que você poderia ver pintado em um carro",
  "Um lugar terrível para despejar as cinzas da vovó",
  "A pior coisa a dizer durante seu discurso no Oscar",
  "O pior trabalho para qualquer caminhoneiro seria entregar ___",
  'Se você pegar fogo, lembre-se: "Pare, solte, role e então ___"',
  "Um calendário de nudez realmente horrível: Os Homens de ___",
  "Um aviso que deve acompanhar todos os futons IKEA",
  "Como seu cônjuge sabe que você está tendo um caso com um palhaço",
  "Uma coisa ruim de se ouvir depois de gritar \"Olá!\" em uma caverna profunda",
  "Uma coisa estranha de se dizer para o cara nu ao seu lado no ônibus",
  "Um sinal que eles deveriam colocar na divisa do estado da Flórida",
  "Como você passaria seu primeiro dia como presidente dos EUA",
  "Um bom nome para um porco-da-terra de estimação",
  "Por que os cartuchos de tinta para impressora são tão caros?",
  "O título de um videogame que teria sido enorme em 1800",
  "Uma coisa estranha de se gritar quando você está no ar durante uma bala de canhão",
  "Uma frase que ninguém na história da humanidade jamais pronunciou",
  "Uma placa de trânsito que faria você virar: \"Cuidado com ___\"",
  'Frase do primeiro rascunho do filme: "Francamente, minha querida, eu ___"',
  "A pior música para perder a virgindade",
  "Um nome terrível para um hotel: Pousada ___",
  "A pior cobertura para colocar em um bolo",
  "AVISO: Nunca coloque ___ em uma panela elétrica",
  "Algo que nem um guaxinim comeria",
  "Algo que seria assustador notar no fundo de uma selfie",
  "O estande que ninguém visita na feira de empregos é de uma empresa chamada ___",
  "Um nome alternativo para bolo de carne",
  "Um bom nome para uma banda cujo vocalista é uma cabra",
  "O nome de uma exposição que você ficaria surpreso em ver em um museu de arte",
  "Uma marca terrível para comida de gato",
  "A última coisa que você quer encontrar na bola de pelo do seu gato",
  "O que um homem das cavernas diz logo após o sexo",
  "Novo superlativo do ensino médio: provavelmente ___",
  "O último sinal que receberemos antes do apocalipse",
  "Um bom nome para uma equipe de roller derby composta por freiras",
  "Um cheiro terrível para ambientador de carro",
  "Uma revisão de três palavras sobre banhos",
  "O próximo spin-off de TV: Lei e Ordem: Unidade Especial ___",
  "A tarefa que o estagiário de Satanás mais odeia",
  "A marca de uma linha patriótica de fraldas",
  "Algo que você não quer ouvir do instrutor de paraquedismo amarrado nas suas costas",
  "Como você pode identificar um Rolex falsificado",
  "A pior atração do carnaval: Cabine ___",
  "A pior hora para dizer a alguém que você deseja o divórcio é no meio de ___",
  "A parte mais importante de um casamento caipira",
  "Que idiota rico bebe champanhe",
  "Como o queijo suíço consegue todos esses buracos?",
  "Um sinal de que seu cachorro é um idiota",
  "Uma atividade divertida que requer apenas três dedos",
  "A primeira coisa que o patinho feio fez depois de se transformar em um lindo cisne",
  "O que as lagostas pensam enquanto são cozidas",
  "A coisa errada a dizer depois de peidar na igreja",
  "Por que não voltamos à lua?",
  "O pior crime da Terra Média",
  "Um nome realmente idiota para uma barbearia",
  "O único trabalho que os robôs nunca tirarão dos humanos",
  "Para se tornar um bilionário em poucos dias, basta ___",
  "Como os antigos marinheiros passavam o tempo em longas viagens",
  "A última coisa que você deseja encontrar em um saco de vácuo",
  "O que as cabras dizem na maior parte do tempo?",
  "A etiqueta mais estranha que você poderia ter em uma caixa de mudança",
  "O som que um buraco negro faz",
  "Um título rejeitado na série Magic School Bus: O Magic School Bus vai para ___",
  "No ano de 2085, ___ será a moeda americana",
  "Uma ótima frase para se inserir em qualquer conversa",
  "Uma coisa perigosa para um drone entregar a você",
  "A última coisa que você quer ouvir enquanto está em uma barraca",
  "Um bom motivo para dar a um restaurante uma avaliação de zero estrelas",
  "Por que fomos colocados aqui nesta Terra?",
  "Truque de vida! Se você não tiver uma garrafeira, basta usar um ___",
  "Escreva uma frase realmente dramática para um médico dizer em um drama médico de TV",
  'O troféu menos impressionante: "1º lugar em ___"',
  "O trabalho mais difícil de fazer andando de patins",
  "A configuração mais estranha de se encontrar em um micro-ondas seria um botão pré-programado para ___",
  "O título do pior livro para ler no banheiro",
  'Proposto novo slogan do Olive Garden: "Quando você está aqui, você é ___"',
  "Uma ideia para um negócio realmente estranho: Rent-a-___",
  "Uma maneira fácil de iniciar um incêndio é esfregar ___",
  "Um bom nome para uma banda cover do Coldplay",
  "Uma boa maneira de ser expulso de uma banda de jazz",
  "A melhor parte de ser um caçador de peles do século XIX",
  "Um terrível sargento estaria constantemente gritando ___",
  "O título do livro mais curto já escrito",
  "Lembre-se, ao comprar uma casa nova, certifique-se sempre de que o proprietário anterior não ___",
  "Uma loja incomum: ___ R'US",
  'Uma palavra que não deveria vir antes de “carne seca”',
  "O pior programa de TV: ___ Dance Party",
  "Por que a vida é tão difícil?",
  "Por que os peixes do seu aquário te odeiam",
  "Um bom uso para 50 galões de gordura de bacon",
  "Um botão estranho no carro de James Bond é simplesmente rotulado ___",
  "Uma nova lei de trânsito que realmente precisa acontecer",
  "Algo que você nunca deve fazer sem luvas",
  "Um aviso que deve vir com queijo em spray",
  "Um ótimo nome para um corretor de imóveis",
  "Um sinal de que seu casamento pode estar desmoronando",
  'As Tartarugas Ninja deveriam atualizar seu bordão de “Cowabunga!” para "___!"',
  "O uso mais idiota da ciência seria clonar um ___",
  "O que você legará ao seu inimigo após sua morte",
  "Uma frase do hino nacional canadense, provavelmente",
  "Um título clickbait sobre vacas",
  "A pior coisa que um gerente de RH poderia usar",
  "A coisa mais inútil para amarrar uma câmera GoPro",
  "Uma coisa preocupante de se notar na etiqueta da sua camisa: 2% ___",
  "A pior coisa a dizer em uma proposta de casamento",
  "A última pessoa com quem você gostaria de estar em um barco salva-vidas",
  "Invente um nome que provavelmente ninguém na história jamais teve",
  "A única coisa que nunca vende em lojas de fantasias é uma máscara de ___",
  'O “talento” mais estranho que uma concorrente de um concurso de beleza poderia exibir',
  "A última coisa que você quer ouvir de alguém sentado na sua frente em um Megabus",
  "Uma coisa estranha de se gritar durante uma briga de cócegas",
  "Uma música apropriada para tocar em um banco de esperma",
  "O que arruinou seu passeio de balão?",
  "A maior reclamação do diabo sobre o Inferno",
  "Uma péssima desculpa para perder a formatura do seu filho",
  "O nome de um show de strip masculino com caras realmente fora de forma",
  "Uma coisa perturbadora ver seu filho fazendo argila",
  'A maneira de comemorar ser homenageado como “Funcionário do Mês do Zoo”',
  "Algo que você não quer encontrar no galpão de ferramentas do seu avô",
  "Sobre o que um homem das cavernas tem pesadelos",
  "A próxima maneira que as companhias aéreas provavelmente tentarão economizar dinheiro: ___",
  "A verdadeira razão pela qual o gigante no topo do pé de feijão estava tentando matar João",
  "Qual é o cheiro da flatulência do unicórnio",
  "Algo que você normalmente não vê nas listas de registro de casais noivos",
  "Que cheiro é esse?",
  "A pergunta mais difícil que um troll de ponte poderia fazer a você",
  "Algo em 98% de todos os bolsos das calças cargo",
  "O lugar mais inapropriado para ter um touro mecânico",
  "Bagels deveriam mudar seu nome para ___",
  "O novo item do cardápio do Taco Bell em 2040 será Frango ___",
  "Conselho terrível de um instrutor de educação de motorista",
  "A única mudança que as igrejas poderiam fazer e que provavelmente faria com que mais pessoas frequentassem",
  "Um uso criativo para uma espiga de milho",
  "A pior coisa para pintar na parede do berçário de um novo bebê",
  "Como você seduz um urso?",
  "O evento mais estranho para acampar na noite anterior",
  "O pior emprego para se ter na Casa Branca",
  "Não jogue fora esses pauzinhos usados! Eles podem ser usados para ___",
  "O que uma tartaruga procura em um companheiro",
  "Últimas notícias! Os cientistas acabam de descobrir a criatura mais feroz da natureza: o ___ tubarão",
  "A pior coisa para acordar e encontrar sentado em seu peito",
  "Um ótimo uso para uma fralda suja",
  "Alerta de conspiração! Alienígenas são reais e são ___",
  "Como seria chamado o 13º mês",
  "A pior coisa para ter escrito na bunda do seu short",
  "A principal causa de morte de Ursinhos Carinhosos",
  "O que você estava procurando não estava dentro de você esse tempo todo. Foi em ___",
  "O nome oficial da roupa íntima do Papa",
  "Um bom nome para uma cidade fictícia na Austrália",
  "Uma ótima maneira de economizar eletricidade é ___",
  "A pior desculpa para abandonar seu encontro",
  "Uma coisa estranha para um astronauta dizer na lua",
  "A Torre Eiffel seria muito mais legal se tivesse ___",
  "O pior título para uma música rap",
  'A pior coisa que você pode ouvir do seu cônjuge: "Estou deixando você por ___"',
  "Você deve sempre ___ antes de se casar",
  "Todo voo de companhia aérea deve vir com um ___ grátis",
  "Uma maneira estranha de manter seus ouvidos aquecidos",
  "O que um idiota diria em um museu",
  "O nome de um bar de solteiros para piratas",
  "Nova regra: você deve ser preso automaticamente se ___",
  "O ingrediente mais estranho para colocar na mistura de trilha",
  "Uma boa frase para quebrar a tensão em um funeral de peixe",
  "É um pássaro, é um avião, ah, espere, não. Deixa pra lá, é só ___",
  "O nome de uma loja de roupas para jóqueis",
  "Um momento inapropriado para usar smoking",
  "O título de um drama claramente prestes a ganhar um Oscar",
  "Um ótimo nome para um meteorologista",
  "O crime mais relatado no bairro do senhor Rogers",
  "O pior veículo para uma corrida de arrancada",
  "Como tornar o golfe mais emocionante",
  "O item mais comum na caixa de Achados e Perdidos no Inferno",
  "O item de menu mais estranho para escolher para sua última refeição",
  "Um passeio secreto do Six Flags que apenas bilionários podem participar",
  "A única coisa que devemos temer é o próprio medo. Ah, e também ___",
  "Um plano estranho para salvar os peixes-boi",
  "Uma coisa estranha para um fantasma sussurrar em seu ouvido",
  "A coisa mais embaraçosa que poderia acontecer no baile",
  "Você obtém os resultados de imagem mais estranhos quando pesquisa por ___",
  "Uma ótima frase de chamariz para usar em uma casa de repouso",
  "O nome de um robô realmente horrível",
  "Um bom sinal de que você acidentalmente se casou com um pato",
  "Um nome terrível para um restaurante panini",
  "Alguns conselhos de vida sólidos: Nunca confie em ___",
  "Um slogan de campanha garantido para elegê-lo presidente",
  "Algo assustador de ouvir uma criança dizer",
  "O que os duendes do Papai Noel fazem fora da temporada",
  "Um nome rejeitado para mamilos",
  "O que os guaxinins que vasculham seu lixo dizem sobre você",
  "Um adesivo que um nudista teria",
  "Um sabor Jelly Belly rejeitado",
  "O título de um álbum gravado por uma cabra cantora",
  "Um novo slogan para a empresa de ônibus Greyhound",
  "Mulheres, nunca namorem um cara que ___",
  "A coisa número um na lista de desejos do Superman",
  "Mais dinheiro, mais ___",
  "Depois de matar Hitler, a segunda coisa que você faria com uma máquina do tempo",
  "A pior foto para ver emoldurada na casa da sua avó",
  "O título de um livro Goosebumps que nunca foi publicado",
  "Todo mundo faz cocô II: ___",
  "A coisa mais assustadora que você pode imaginar é ___ andar ___",
  "Alfred pode conhecer a identidade secreta do Batman, mas o maior segredo que ele guarda é ___",
  "Nome de luta livre da Rainha Elizabeth",
  "Um bom nome para uma bala para sua bunda",
  "Uma promessa que você não deveria fazer a uma criança doente",
  "A pior coisa para deixar escapar ao assistir a uma cena de sexo de filme com seus pais",
  "A pior frase de efeito para um capitão de Star Trek",
  "O nome de um cereal para serial killers",
  'O pior jogo infantil: "Hungry, Hungry ___"',
  "Um filme estranho de Tom Hanks/Meg Ryan: Sleepless in ___",
  "O título de um filme inédito do Air Bud",
  "A pior pergunta a ser feita em uma entrevista de emprego como salva-vidas",
  "O que você não deve dizer ao ser batizado",
  "Uma regra nova e empolgante para o Monopólio: passe, vá e colete ___",
  "O que um contrabandista muito ruim diria a um guarda de fronteira",
  "O título de um filme erótico para elefantes",
  "O nome de uma loja de lingerie para ursos",
  "Uma posição sexual para fantasmas",
  "Uma pergunta estranha de se encontrar em um teste de QI",
  "A pior coisa para ver usando óculos de raio-x",
  "Quem é o chefe?",
  "Você sabe que encontrou sua alma gêmea quando olha nos olhos dela e ela diz ___",
  "O pior interrogatório teria um policial bom, um policial mau e um policial ___",
  "Não fale comigo antes de eu tomar meu café e não me toque até eu tomar meu ___",
  "Algo que você nunca deve dizer quando for parado por um xerife de uma pequena cidade",
  "Os funcionários da IKEA odeiam quando você ___",
  "A parte mais difícil de ter cinco famílias secretas",
  "Algo que você não deveria dizer a um padrinho da máfia",
  "Um sinal de que você pode ser uma péssima babá",
  "Um sinal de que você pode estar em uma seita",
  "Título de um programa da HGTV para abelhas",
  "Uma coisa terrível de se dizer ao testar um colchão",
  "Um nome terrível para uma droga de rua",
  "O próximo grande reality show: America tem ___",
  "Por que você não tem permissão para voltar ao Jurassic Park",
  "A única coisa que deprime Popeye",
  'Conselho estranho do seu avô: "Não pegue ___ de madeira"',
  "A conversa estimulante que você receberia de um treinador de futebol que aposta no outro time",
  "Se você quiser sobreviver à prisão, vá até o prisioneiro mais assustador e ___",
  "AVISO: O governo permite que a merenda escolar contenha até 4% ___",
  "Deveria haver cartões comemorativos específicos para esta situação",
  'Um primeiro rascunho rejeitado de The Shining: "Aqui está ___!"',
  "Como você sabe que seu trailer está assombrado",
  "O que deveria ser despejado sobre o treinador perdedor no final de um jogo de futebol",
  "A pior coisa para escrever na seção de gorjetas de um cheque",
  'Um hino da igreja rejeitado: "Swing Low, Sweet ___"',
  "O pior lugar para adormecer",
  "Uma pergunta que o Charada faz no primeiro encontro",
  "A declaração de abertura de um mau advogado ao júri",
  "As últimas palavras de Elvis, provavelmente",
  "Uma coisa chocante de ver vasculhando seu lixo à noite",
  "A coisa perfeita a dizer para se livrar dos advogados que atendem de porta em porta",
  "Um novo nome para bananas",
  "Uma coisa idiota de se dizer antes de sua grande corrida de arrancada",
  "As eleições seriam muito melhores se, em vez de debates, tornássemos os candidatos ___",
  "O nome de uma boate para pessoas na faixa dos 40 anos",
  "O pior escritório tem vista para ___",
  "Por que Wolverine não consegue fazer um relacionamento funcionar",
  "A única coisa sobre a qual o sentido de aranha do Homem-Aranha nunca o avisa",
  "O nome de um bar sem banheiro",
  "Wife Swap é um programa muito melhor do que ___ Swap",
  "Um nome terrível para um iate: SS ___",
  "Algo que você não quer ouvir do cara que dirige sua romântica carruagem puxada por cavalos",
  "O nome de um salão de cabeleireiro esnobe para gatos",
  "A pior coisa a dizer ao entrar em um bar de motociclistas difícil",
  'Uma coisa interessante na avaliação de desempenho no trabalho do Robocop: “Precisa trabalhar em ___”',
  "A pior coisa a dizer enquanto é torturado",
  "Um nome rejeitado para uma cor Crayola",
  "Um bom nome para uma marca de whisky muito barata",
  'Um slogan político se um urso estivesse concorrendo à presidência: "Make America ___ Again"',
  "Explique como os bebês são feitos em três palavras",
  "O homem perfeito é alto, moreno e ___",
  "No futuro, os robôs farão tudo por nós, exceto ___",
  "Um bom sinal de que seu cachorro usa suas roupas quando você não está em casa",
  "O nome de um cavalo em que você nunca deve apostar",
  "Um nome melhor para umbigos",
  "Você sabe que tem um proprietário duvidoso quando ___",
  "É fofo quando a vovó tricota um lenço para você. É muito estranho quando ela te tricota ___",
  "Você sabe que está velho quando está em um bar e o barman te pergunta ___",
  "Você sabe que está hospedado em um hotel sujo quando eles oferecem um ___ continental grátis",
  "Você sabe que sua empresa está fechando quando você chega para trabalhar e percebe ___",
  "Uma ótima coisa para um pai dizer para assustar o acompanhante do baile de formatura de seu filho",
  "Uma boa piada para contar enquanto você está amarrado em um porão",
  "Uma ótima maneira de ser expulso de Hogwarts",
  "Uma herança de família que você provavelmente não deveria transmitir aos seus filhos",
  "Um sinal de que seu Roomba pode estar senciente",
  'Uma má maneira de começar seu discurso de orador seria "Senhoras e senhores, eu ___"',
  "Por que o Homem de Lata não é casado",
  "O apelido de Frankenstein no ensino médio",
  "Harry Potter pode fazer um feitiço muito estranho e obscuro que lhe permite ___",
  "Quando você tosse sangue, você deve se preocupar. Quando você tosse ___ você deveria ficar apavorado",
  "O nome de um filme de animação estrelado por uma vaca surfista",
  "Uma frase estranha que Jesus diria antes de realizar um milagre",
  "O que você diz três vezes para convocar Donald Trump",
  "As únicas coisas que podem sobreviver à guerra nuclear são baratas e ___",
  "O que NÃO dizer em um encontro enquanto você está em um barco a remo",
  'Uma manchete estranha de se ver na capa da Cosmo: “17 truques para ___”',
  "Como os fantasmas do Pac-Man morreram?",
  "Um novo termo para quando você está bêbado de mimosas",
  "Um sinal que você nunca vê: \"Buzine se você for ___\"",
  "A sequência de Shakespeare Apaixonado se chamaria Shakespeare em ___",
  "Uma coisa fofa que um advogado diria enquanto abraça você",
  "Seu incrível e novo nome do Programa de Relocação de Testemunhas",
  "A pior parte de ter seu cérebro humano vivendo em um corpo de robô",
  'Se um entrevistador perguntar "Qual é a sua maior fraqueza?", diga sempre ___',
  "Qual título de filme descreve melhor o estado da sua bunda agora?",
  "Você sabe que é amor quando você nem hesita quando seu amante lhe pede ___",
  "Algo que você nunca quer ouvir um comissário de bordo dizer",
  "Gritar fogo em um cinema lotado é ruim, mas pior ainda é gritar ___",
  "Um castelo inflável é legal, mas um ___ inflável é simplesmente triste",
  "Se Michigan tem o formato de uma mão, o Texas deveria ter o formato de ___",
  "Você sabe que tem um filho bagunceiro quando lhe dão um desenho de giz de cera de ___",
  "O que um adolescente mal-humorado diria para machucar seu padrasto, Pé Grande",
  "O pior lugar para colocar salada de batata",
  "A coisa mais triste de se dizer com uma voz cheia de hélio",
  "Com o que Twinkies devem ser preenchidos",
  "Você sabe que está enlouquecendo quando ouve o Rice Krispies dizer ___",
  "A pior coisa a dizer no banco de trás de um carro de polícia",
  "Uma marca de calças para sereias",
  "O nome de um grupo de apoio para homens que não conseguem deixar crescer a barba",
  "Se você quiser um espantalho realmente eficaz, certifique-se de que ele se pareça com ___",
  "A pior hora para ouvir uma câmera disparar",
  'O pior coquetel que termina em “-tini”',
  "Uma ótima maneira de deixar um golfinho louco é ___",
  "É uma coisa ruim ouvir a pessoa que corta seu cabelo dizer",
  'Uma ótima maneira de apimentar o beisebol é a regra "Três rebatidas e você é ___"',
  "Como Papai Smurf planeja passar sua aposentadoria",
  "A razão pela qual os alienígenas pararam de sequestrar você",
  'Uma resposta terrível ao texto "Você está acordado?"',
  "Um mistério que Nancy Drew não conseguiu resolver: O Caso do ___",
  "O pior brinquedo que você poderia encontrar em uma caixa de cereal",
  "O título de um livro de receitas escrito por um cowboy",
  "Um nome terrível para uma empresa de perucas",
  "Uma característica única em um sofá para bilionários",
  "O nome de um restaurante fast food onde os trabalhadores não usam calças",
  "A melhor maneira de irritar o garçom de um restaurante esnobe é continuar perguntando ___",
  'Um título rejeitado e menos assustador para o filme Tubarão',
  "O título de um livro que conta tudo de um ex-My Little Pony",
  "O nome de um feriado que você inventa rapidamente para sair do trabalho",
  "A pior coisa para cheirar quando você entra no carro",
  'Frase do primeiro rascunho do filme: "Vá em frente. Faça meu ___"',
  "Uma coisa terrível de se dizer ao segurança que verifica sua identidade falsa",
  "Uma má maneira de fazer amizade com seu novo vizinho",
  "O título de um filme de ação estrelado por sapos",
  "A vela perfumada menos popular cheira a ___",
  "O título de um drama de TV sobre um fazendeiro que se torna policial",
  "Uma coisa estranha de se encontrar em uma pintura rupestre",
  "A pior desculpa que Clark Kent deu a Lois Lane para que ele pudesse se transformar no Superman",
  "A pior coisa que você poderia tentar doar ao Exército da Salvação",
  "Truque de vida! Um baller de melão comum também pode ser usado para ___",
  "Um bom sinal de que há um homem invisível morando no seu apartamento",
  "A coisa errada a dizer aos sequestradores que estão com seu marido",
  "A coisa mais decepcionante de ganhar em um programa de premios: um suprimento vitalício de ___",
  "Quando confrontado por um leão da montanha, mantenha a calma, fique o mais alto possível e ___",
  'Um velho ditado que sua avó lhe ensinou: "Olhe diante de você ___"',
  "Um veículo de super-herói rejeitado: o ___mobile",
  "Você sabe que é hora de perder peso quando seu intestino bloqueia sua visão de ___",
  'Uma cirurgia estranha que começa com “Laser”',
  "O que você pode ouvir Big Bird dizer em seu leito de morte",
  "A pior maneira de morrer: morte por mil ___",
  "Um nome ruim para um proctologista: Dr.",
  "A maior reclamação de Branca de Neve sobre viver com os Sete Anões",
  "A pior coisa é ficar preso no cabelo",
  "Uma boa provocação para gritar com os elefantes do zoológico",
  "O passeio mais popular em um parque temático religioso",
  "A pior coisa a dizer durante a audiência de confirmação do juiz da Suprema Corte",
  "A música mais inadequada para tocar bateria aérea",
  "Um bom substituto para os shows de baleias do Sea World seria ___",
  "A pior despedida de solteiro envolveria ___",
  "Como se chamaria o restaurante de brunch mais detestavelmente moderno do mundo",
  "Uma coisa estranha para se manter como animal de estimação",
  "Um trabalho que não existe agora, mas que provavelmente alguém teve antigamente",
  "Um bom nome para um robô sexual",
  "O pior motivo para ligar para o 911",
  "O que a lebre fez da vida depois de perder para a tartaruga",
  "A melhor parte de ser Donald Trump",
  "Um filme que precisava de mais nudez",
  "A pior pessoa que poderia cantar o tema de James Bond",
  "Um novo clássico infantil: O Aveludado ___",
  "O título de um livro Goosebumps que nunca foi publicado",
  "O que o S significa em Ulysses S. Grant",
  "Um bom nome para uma bala para sua bunda",
  "Um sabor Jelly Belly rejeitado",
  "A pior frase de efeito para um capitão de Star Trek",
] as const;
